service: pinger-update-server


provider:
  name: aws
  runtime: nodejs4.3
  region: us-east-1
  profile: claudia
  environment:
    NODE_ENV: production
    basePath: dev/
  cfLogs: true

functions:
  hello:
    handler: lambda.handler
    events:
      - http:
         path: index
         method: get
         integration: lambda-proxy
      - http:
         path: /
         method: get
         integration: lambda-proxy
      - http:
         path: update/darwin
         method: get
         integration: lambda-proxy
      - http:
         path: users
         method: get
         integration: lambda-proxy
      - http:
         path: stylesheets/{proxy+}
         method: get
         integration: lambda-proxy
      - http:
         path: assests/{proxy+}
         method: get
         integration: lambda-proxy
custom:
  serverless-offline:
    babelOptions:
      presets: ["es2015", "stage-2"]